[versions]

# Shared
fabricLoader = "0.19.5"
loom = "1.17-SNAPSHOT"

# Dev Dependencies
devauth = "1.2.2"

[libraries]

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }

[plugins]
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
